const books = [
  {
    id: 1,
    title: "Teaching Mrs. Tingle",
    author: "Hervey Beaney",
    img: null,
    price: "£9.06",
  },
  {
    id: 2,
    title: "Question of Silence, A (De stilte rond Christine M.)",
    author: "Murial Denson",
    img: null,
    price: "£12.12",
  },
  {
    id: 3,
    title: "Grandmother",
    author: "Neely Cristofanini",
    img: null,
    price: "£20.08",
  },
  {
    id: 4,
    title: "Magic Christmas Tree, The",
    author: "Genevra Ottley",
    img: null,
    price: "£6.62",
  },
  {
    id: 5,
    title: "Hit by Lightning",
    author: "Wynn Seiler",
    img: null,
    price: "£35.10",
  },
  {
    id: 6,
    title: "Messenger, The",
    author: "Alane Blodgetts",
    img: null,
    price: "£10.53",
  },
  {
    id: 7,
    title: "Sleepaway Camp",
    author: "Rob Cleave",
    img: null,
    price: "£35.53",
  },
  {
    id: 8,
    title: "Blood from the Mummy's Tomb",
    author: "Francene Confait",
    img: null,
    price: "£29.60",
  },
  {
    id: 9,
    title: "My Führer",
    author: "Johnathan Bolesworth",
    img: null,
    price: "£19.28",
  },
  {
    id: 10,
    title: "Chouga (Shuga)",
    author: "Vernon Laweles",
    img: null,
    price: "£13.21",
  },
  {
    id: 11,
    title: "Fat People (Gordos)",
    author: "Dulce Maccrae",
    img: null,
    price: "£19.89",
  },
  {
    id: 12,
    title: "Getting Go, the Go Doc Project",
    author: "Lurline Doding",
    img: null,
    price: "£49.59",
  },
  {
    id: 13,
    title: "Last Dragon, The",
    author: "Alvira Defau",
    img: null,
    price: "£43.19",
  },
  {
    id: 14,
    title: "Girls Against Boys ",
    author: "Manya Joe",
    img: null,
    price: "£39.31",
  },
  {
    id: 15,
    title: "In the Land of Women",
    author: "Lorrin Slany",
    img: null,
    price: "£28.30",
  },
  {
    id: 16,
    title: "Lilya 4-Ever (Lilja 4-ever)",
    author: "Rosette Sneaker",
    img: null,
    price: "£12.53",
  },
  {
    id: 17,
    title: "Alice Adams",
    author: "Jule Mongain",
    img: null,
    price: "£24.89",
  },
  {
    id: 18,
    title: "Wondrous Oblivion",
    author: "Agathe Milstead",
    img: null,
    price: "£19.88",
  },
  {
    id: 19,
    title: "My Friends (Amici miei)",
    author: "Doll Fleeman",
    img: null,
    price: "£45.73",
  },
  {
    id: 20,
    title: "Good Evening, Mr. Wallenberg (God afton, Herr Wallenberg)",
    author: "Tallie Acum",
    img: null,
    price: "£49.57",
  },
  {
    id: 21,
    title: "Last Klezmer: Leopold Kozlowski, His Life and Music, The",
    author: "Joshia Marchant",
    img: null,
    price: "£25.36",
  },
  {
    id: 22,
    title: "Father, The (Pedar)",
    author: "Julissa Louca",
    img: null,
    price: "£26.71",
  },
  {
    id: 23,
    title: "Earthsea (Legend of Earthsea)",
    author: "Lise Blackall",
    img: null,
    price: "£10.82",
  },
  {
    id: 24,
    title: "It's a Boy Girl Thing",
    author: "Seumas Piell",
    img: null,
    price: "£35.48",
  },
  {
    id: 25,
    title: "Sometime in August (Mitte Ende August)",
    author: "Hendrick Shorten",
    img: null,
    price: "£14.26",
  },
  {
    id: 26,
    title: "Man of a Thousand Faces",
    author: "Tori Twaits",
    img: null,
    price: "£5.96",
  },
  {
    id: 27,
    title: "Blind Massage (Tui na)",
    author: "Emyle Cammiemile",
    img: null,
    price: "£12.58",
  },
  {
    id: 28,
    title: "Arise, My Love",
    author: "Rivalee Aubury",
    img: null,
    price: "£37.11",
  },
  {
    id: 29,
    title: "Concert, Le",
    author: "Pepillo Goldsbrough",
    img: null,
    price: "£45.75",
  },
  {
    id: 30,
    title: "Edge of the City",
    author: "Robert Mc Caghan",
    img: null,
    price: "£45.74",
  },
];

books.forEach(
  (book) =>
    (book.img =
      "https://images.freeimages.com/images/small-previews/653/historical-book-cover-1566109.jpg")
);

module.exports = books;
